language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run lint
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
